const fs = require('fs');
const path = require('path');

const compileImage = (pngSubPath, mapSubPath, jsSubPath, base64VarName, mapVarName, blockstatesVarName, modelsVarName) => {
    const pngPath = path.join(__dirname, 'assets', pngSubPath);
    const mapPath = path.join(__dirname, 'assets', mapSubPath);
    const jsPath = path.join(__dirname, 'assets', jsSubPath);
    
    const baseDir = path.dirname(pngPath);
    const blockstatesPath = path.join(baseDir, 'blockstates.json');
    const modelsPath = path.join(baseDir, 'models.json');
    
    try {
        if (!fs.existsSync(pngPath)) {
            console.error(`❌ Error: Could not find assets/${pngSubPath} at: ${pngPath}`);
            return false;
        }
        
        console.log(`⏳ Compiling ${pngSubPath} and ${mapSubPath} -> ${jsSubPath}...`);
        
        // Read PNG & convert to base64
        const imgBuffer = fs.readFileSync(pngPath);
        const base64Data = imgBuffer.toString('base64');
        
        // Read mapping JSON (default to empty object if not exists)
        let mappingJson = '{}';
        if (fs.existsSync(mapPath)) {
            mappingJson = fs.readFileSync(mapPath, 'utf8');
        } else {
            console.warn(`   ⚠️ Warning: Mapping file ${mapSubPath} not found, generating empty mapping.`);
        }
        
        // Read blockstates and models
        let blockstatesJson = '{}';
        if (fs.existsSync(blockstatesPath)) {
            blockstatesJson = fs.readFileSync(blockstatesPath, 'utf8');
        } else {
            console.warn(`   ⚠️ Warning: Blockstates file not found at ${blockstatesPath}`);
        }
        
        let modelsJson = '{}';
        if (fs.existsSync(modelsPath)) {
            modelsJson = fs.readFileSync(modelsPath, 'utf8');
        } else {
            console.warn(`   ⚠️ Warning: Models file not found at ${modelsPath}`);
        }
        
        // Ensure parent directory exists for jsPath
        const parentDir = path.dirname(jsPath);
        if (!fs.existsSync(parentDir)) {
            fs.mkdirSync(parentDir, { recursive: true });
        }

        const outputJs = `// Automatically generated by compile_atlas.js. Do not edit directly.
window.${base64VarName} = "data:image/png;base64,${base64Data}";
window.${mapVarName} = ${mappingJson.trim()};
window.${blockstatesVarName} = ${blockstatesJson.trim()};
window.${modelsVarName} = ${modelsJson.trim()};
`;
        
        fs.writeFileSync(jsPath, outputJs, 'utf8');
        console.log(`   ✅ Compiled to assets/${jsSubPath} (Variables: window.${base64VarName}, window.${mapVarName}, window.${blockstatesVarName}, window.${modelsVarName})`);
        return true;
    } catch (err) {
        console.error(`   ❌ Failed to compile ${pngSubPath}:`, err);
        return false;
    }
};

console.log("🚀 Starting Atlas & Mapping Base64 Compiler...");
console.log("--------------------------------------------------");

const baseOk = compileImage('vanilla/atlas.png', 'vanilla/atlas-map.json', 'vanilla/atlas-base64.js', 'ATLAS_BASE64', 'ATLAS_MAP', 'ATLAS_BLOCKSTATES', 'ATLAS_MODELS');

// Compile technical mode only if the source file exists
const techPngPath = path.join(__dirname, 'assets', 'tech', 'atlas.png');
let techOk = true;
if (fs.existsSync(techPngPath)) {
    techOk = compileImage('tech/atlas.png', 'tech/atlas-map.json', 'tech/atlas-technical-base64.js', 'ATLAS_TECHNICAL_BASE64', 'ATLAS_TECHNICAL_MAP', 'ATLAS_TECHNICAL_BLOCKSTATES', 'ATLAS_TECHNICAL_MODELS');
} else {
    console.log("ℹ️ Technical atlas (assets/tech/atlas.png) not found. Skipping technical compile.");
}

console.log("--------------------------------------------------");
if (baseOk && techOk) {
    console.log("🎉 Compiling complete!");
} else {
    console.warn("⚠️ Base texture failed to compile. Please check the errors above.");
}
